# Generated by Django 4.0.6 on 2022-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('availability_qty', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=10)),
                ('available_data', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
