# Generated by Django 4.0.6 on 2022-07-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='damage',
            field=models.BooleanField(max_length=10),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.BooleanField(max_length=10),
        ),
    ]
