# Generated by Django 4.0.6 on 2022-07-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_component_damage_alter_component_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='availability_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='available_data',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
