# Generated by Django 4.0.6 on 2022-07-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_component_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
